### PR TITLE
fix: Validation error of user request returns HTTP 500

### LINKED ISSUE #149: Validation error of user request returns HTTP 500
Currently HTTP code 500 (internal server error) is returned when a user submits an invalid request. A 400 code (Bad Request) should be returned instead.

### PR DESCRIPTION
**Pull request by sandrask**
Fixed resolution and resolution with initial state to return bad request in case that user supplies invalid input

Operation processing has been fixed with issue #201 (operation validation on server side)

Closes #149

Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>

### CODE REVIEW

File: pkg/restapi/dochandler/resolvehandler.go [hunk 1]
```diff
@@ -60,6 +60,9 @@ func (o *ResolveHandler) doResolve(id string) (*document.ResolutionResult, error
 
 	doc, err := o.resolver.ResolveDocument(id)
 	if err != nil {
+		if strings.Contains(err.Error(), "bad request") {
```
Comment (bstasyszyn) [inline pkg/restapi/dochandler/resolvehandler.go:63]: Can we instead define a 'BadRequest' error and then use errors.Is(...) to determine that it's the cause? I find that matching a string within the error is not reliable. I was already thinking about refactoring the code that searches for "not found".

Comment (sandrask) [reply pkg/restapi/dochandler/resolvehandler.go:63]: Should I provide details about error. We usually use this pattern if error is constant e.g. 
var ErrNotFound = errors.New("did not found under given key")

Comment (bstasyszyn) [reply pkg/restapi/dochandler/resolvehandler.go:63]: I think that a new 'BadRequestError' type should be defined which has a code. The code contains a specific value that's defined in an enumeration. This is what's done for the cas REST endpoint: https://github.com/trustbloc/sidetree-fabric/blob/master/pkg/rest/dcashandler/retrieveerror.go

Comment (sandrask) [reply pkg/restapi/dochandler/resolvehandler.go:63]: You have 5 status codes there. If I would capture all validations it would probably be more than 30 status codes plus they are all over the place because of the nature of resolution with initial state (parse did, parse initial state parameter, validate initial document, parse operation which involves suffix, delta patches (keys, services), reveal values, commitment values, hashes etc). I can create new issue for that and we can address it later on.

Comment (bstasyszyn) [reply pkg/restapi/dochandler/resolvehandler.go:63]: OK, this can be done later.

Comment (sandrask) [reply pkg/restapi/dochandler/resolvehandler.go:63]: Created #264
